set_property IOSTANDARD LVCMOS33 [get_ports {cin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cin[0]}]
set_property PACKAGE_PIN M4 [get_ports {cin[2]}]
set_property PACKAGE_PIN N4 [get_ports {cin[1]}]
set_property PACKAGE_PIN R1 [get_ports {cin[0]}]

set_property PACKAGE_PIN D4 [get_ports {num1[0]}]
set_property PACKAGE_PIN E3 [get_ports {num1[1]}]
set_property PACKAGE_PIN D3 [get_ports {num1[2]}]
set_property PACKAGE_PIN F4 [get_ports {num1[3]}]
set_property PACKAGE_PIN F3 [get_ports {num1[4]}]
set_property PACKAGE_PIN E2 [get_ports {num1[5]}]
set_property PACKAGE_PIN D2 [get_ports {num1[6]}]


set_property IOSTANDARD LVCMOS33 [get_ports {num1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num1[6]}]

set_property PACKAGE_PIN B4 [get_ports {num2[0]}]
set_property PACKAGE_PIN A4 [get_ports {num2[1]}]
set_property PACKAGE_PIN A3 [get_ports {num2[2]}]
set_property PACKAGE_PIN B1 [get_ports {num2[3]}]
set_property PACKAGE_PIN A1 [get_ports {num2[4]}]
set_property PACKAGE_PIN B3 [get_ports {num2[5]}]
set_property PACKAGE_PIN B2 [get_ports {num2[6]}]


set_property IOSTANDARD LVCMOS33 [get_ports {num2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports light1]
set_property IOSTANDARD LVCMOS33 [get_ports light2]
set_property PACKAGE_PIN H1 [get_ports light1]
set_property PACKAGE_PIN G1 [get_ports light2]


set_property PACKAGE_PIN F6 [get_ports {leftled[2]}]
set_property PACKAGE_PIN G4 [get_ports {leftled[1]}]
set_property PACKAGE_PIN G3 [get_ports {leftled[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leftled[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leftled[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leftled[0]}]
set_property PACKAGE_PIN K2 [get_ports {rightled[2]}]
set_property PACKAGE_PIN J2 [get_ports {rightled[1]}]
set_property PACKAGE_PIN J3 [get_ports {rightled[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rightled[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rightled[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rightled[0]}]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
